print("x" + 5* " " + "x") 
print(" " + "x" + 3* " " + "x")
print(2* " " + "x" + " " + "x")
print(3* " " + "x")
print(2* " " + "x" + " " + "x")
print(" " + "x" + 3* " " + "x")
print("x" + 5* " " + "x") 
