print("I am 11 years old")
print("I am going to Evergreen Middle School")
print("I have a 7 year old brother")
print("My favorite sports are tennis, swimming, and basketball")
print("I love to travel")
print("I enjoy playing videogames")
print("I love playing outside with friends")
print("My favorite subject is math")
print("I am going to 6th grade")
print("I like to read")
